extends RefCounted

const VFX_ROOT := "res://game_assets/VFX/Alenia_VFX_Elements_Pack/Frames_Individuales"
const SFX_ROOT := "res://game_assets/SFX/RPG Sounds"

const EFFECT_FOLDERS := {
	&"attack": "vfx_dark_slash_30f_64px",
	&"cane_tap": "vfx_dark_slash_30f_64px",
	&"pummel": "vfx_dark_slash_30f_64px",
	&"cleave": "vfx_dark_slash_30f_64px",
	&"raptor_pounce": "vfx_dark_slash_30f_64px",
	&"static_discharge": "vfx_electric_zap_30f_64px",
	&"voltaic_cage": "vfx_electric_zap_30f_64px",
	&"field_triage": "vfx_arcane_heal_30f_64px",
	&"tonic": "vfx_arcane_heal_30f_64px",
	&"ether": "vfx_arcane_heal_30f_64px",
	&"phoenix_tonic": "vfx_holy_pillar_30f_64px",
	&"smelling_salts": "vfx_neural_pulse_30f_64px",
	&"rally": "vfx_neural_pulse_30f_64px",
	&"raptor_distract": "vfx_neural_pulse_30f_64px",
	&"spectral_touch": "vfx_soul_vortex_30f_64px",
	&"late_fee": "vfx_soul_vortex_30f_64px",
	&"ink_blight": "vfx_toxic_bubbles_30f_64px",
	&"steal_time": "vfx_chrono_shatter_30f_64px",
	&"borrowed_second": "vfx_chrono_shatter_30f_64px",
	&"club_smash": "vfx_dark_slash_30f_64px",
	&"primal_roar": "vfx_neural_pulse_30f_64px",
	&"mammoth_slam": "vfx_dark_slash_30f_64px",
	&"prehistoric_bite": "vfx_dark_slash_30f_64px",
	&"tail_sweep": "vfx_dark_slash_30f_64px",
	&"stampede": "vfx_neural_pulse_30f_64px",
	&"commuter_roar": "vfx_neural_pulse_30f_64px",
	&"oni_crescent": "vfx_dark_slash_30f_64px",
	&"blood_moon_cleave": "vfx_dark_slash_30f_64px",
	&"rift_bite": "vfx_dark_slash_30f_64px",
	&"phase_scratch": "vfx_soul_vortex_30f_64px",
	&"faultline_pounce": "vfx_chrono_shatter_30f_64px",
	&"anchor_howl": "vfx_neural_pulse_30f_64px",
	&"mossback_pummel": "vfx_dark_slash_30f_64px",
	&"spore_receipt": "vfx_toxic_bubbles_30f_64px",
	&"rooted_red_tape": "vfx_toxic_bubbles_30f_64px",
	&"hearty_provisions": "vfx_arcane_heal_30f_64px",
	&"cobalt_claw": "vfx_dark_slash_30f_64px",
	&"express_jolt": "vfx_electric_zap_30f_64px",
	&"priority_delivery": "vfx_electric_zap_30f_64px",
	&"emergency_dispatch": "vfx_arcane_heal_30f_64px",
	&"warden_pummel": "vfx_dark_slash_30f_64px",
	&"piston_surge": "vfx_electric_zap_30f_64px",
	&"bulkhead_drop": "vfx_dark_slash_30f_64px",
	&"pressure_lock": "vfx_chrono_shatter_30f_64px",
	&"foxfire": "vfx_soul_vortex_30f_64px",
	&"nine_tail_judgment": "vfx_soul_vortex_30f_64px",
	&"viper_rush": "vfx_neural_pulse_30f_64px",
	&"viper_uppercut": "vfx_dark_slash_30f_64px",
	&"seraph_strike": "vfx_holy_pillar_30f_64px",
	&"heavenly_aegis": "vfx_holy_pillar_30f_64px",
	&"frost_nova": "vfx_chrono_shatter_30f_64px",
	&"soul_reaper": "vfx_soul_vortex_30f_64px",
	&"compliance_burst": "vfx_electric_zap_30f_64px",
	&"daylight_lance": "vfx_holy_pillar_30f_64px",
	&"permanent_noon": "vfx_holy_pillar_30f_64px",
	&"cold_assessment": "vfx_chrono_shatter_30f_64px",
	&"lien_of_silence": "vfx_soul_vortex_30f_64px",
	&"absolute_audit": "vfx_chrono_shatter_30f_64px",
	&"memory_stamp": "vfx_neural_pulse_30f_64px",
	&"procession_waltz": "vfx_soul_vortex_30f_64px",
	&"final_testimony": "vfx_chrono_shatter_30f_64px",
}

const ACTION_SOUNDS := {
	&"attack": "sword_swing.mp3",
	&"cane_tap": "sword_hit.mp3",
	&"pummel": "sword_hit.mp3",
	&"cleave": "sword_swing.mp3",
	&"raptor_pounce": "sword_hit.mp3",
	&"static_discharge": "lightning_cast.mp3",
	&"voltaic_cage": "lightning_cast.mp3",
	&"field_triage": "potion.mp3",
	&"tonic": "potion.mp3",
	&"ether": "potion.mp3",
	&"phoenix_tonic": "arcane_status.mp3",
	&"smelling_salts": "arcane_status.mp3",
	&"rally": "arcane_status.mp3",
	&"raptor_distract": "arcane_status.mp3",
	&"spectral_touch": "arcane_status.mp3",
	&"late_fee": "arcane_status.mp3",
	&"ink_blight": "arcane_status.mp3",
	&"steal_time": "arcane_status.mp3",
	&"borrowed_second": "arcane_status.mp3",
	&"club_smash": "sword_hit.mp3",
	&"primal_roar": "arcane_status.mp3",
	&"mammoth_slam": "sword_hit.mp3",
	&"prehistoric_bite": "sword_hit.mp3",
	&"tail_sweep": "sword_swing.mp3",
	&"stampede": "sword_hit.mp3",
	&"commuter_roar": "arcane_status.mp3",
	&"oni_crescent": "sword_swing.mp3",
	&"blood_moon_cleave": "sword_swing.mp3",
	&"rift_bite": "sword_hit.mp3",
	&"phase_scratch": "arcane_status.mp3",
	&"faultline_pounce": "sword_swing.mp3",
	&"anchor_howl": "arcane_status.mp3",
	&"mossback_pummel": "sword_hit.mp3",
	&"spore_receipt": "arcane_status.mp3",
	&"rooted_red_tape": "arcane_status.mp3",
	&"hearty_provisions": "potion.mp3",
	&"cobalt_claw": "sword_hit.mp3",
	&"express_jolt": "lightning_cast.mp3",
	&"priority_delivery": "lightning_cast.mp3",
	&"emergency_dispatch": "potion.mp3",
	&"warden_pummel": "sword_hit.mp3",
	&"piston_surge": "lightning_cast.mp3",
	&"bulkhead_drop": "sword_hit.mp3",
	&"pressure_lock": "arcane_status.mp3",
	&"foxfire": "arcane_status.mp3",
	&"nine_tail_judgment": "arcane_status.mp3",
	&"viper_rush": "sword_hit.mp3",
	&"viper_uppercut": "sword_hit.mp3",
	&"seraph_strike": "lightning_cast.mp3",
	&"heavenly_aegis": "arcane_status.mp3",
	&"frost_nova": "arcane_status.mp3",
	&"soul_reaper": "arcane_status.mp3",
	&"compliance_burst": "lightning_cast.mp3",
	&"daylight_lance": "lightning_cast.mp3",
	&"permanent_noon": "arcane_status.mp3",
	&"cold_assessment": "arcane_status.mp3",
	&"lien_of_silence": "arcane_status.mp3",
	&"absolute_audit": "lightning_cast.mp3",
	&"memory_stamp": "arcane_status.mp3",
	&"procession_waltz": "arcane_status.mp3",
	&"final_testimony": "lightning_cast.mp3",
}


static func effect_frames(action_id: StringName) -> Array[String]:
	var folder := String(EFFECT_FOLDERS.get(action_id, ""))
	var paths: Array[String] = []
	if folder.is_empty():
		return paths
	for index in range(30):
		paths.append("%s/%s/frame_%02d.png" % [VFX_ROOT, folder, index])
	return paths


static func action_sound(action_id: StringName) -> String:
	var filename := String(ACTION_SOUNDS.get(action_id, ""))
	return "" if filename.is_empty() else "%s/%s" % [SFX_ROOT, filename]


static func victory_sound() -> String:
	return "%s/victory.mp3" % SFX_ROOT
