class_name CampaignBestiaryCatalog
extends RefCounted

## Stable enemy definitions are content records. Actor construction, profile
## resolution, and battle animation paths remain the combat database's runtime
## responsibilities.

static var DEFINITIONS := {
		&"schoolgirl_ghost": {"name": "Restless Apparition", "hp": 92, "attack": 18, "defense": 10, "magic": 23, "spirit": 13, "speed": 25, "sprite_profile": &"schoolgirl_ghost_battle_actor", "actions": [&"spectral_touch"], "elements": {&"lightning": 1.5, &"spectral": 0.5}, "exp": 22, "duckets": 8},
		&"war_book": {"name": "Unabridged Menace", "hp": 118, "attack": 24, "defense": 17, "magic": 12, "spirit": 15, "speed": 19, "sprite_profile": &"war_book_battle_actor", "actions": [&"hurl_volume", &"ink_blight"], "elements": {&"lightning": 0.75, &"spectral": 0.75}, "exp": 28, "duckets": 11},
		&"clock_mirror": {"name": "The Late Reflection", "hp": 175, "attack": 19, "defense": 20, "magic": 29, "spirit": 21, "speed": 31, "sprite_profile": &"clock_mirror_battle_actor", "actions": [&"steal_time", &"spectral_touch"], "elements": {&"lightning": 1.5, &"time": 0.5}, "exp": 52, "duckets": 19},
		&"composer_portrait": {"name": "Unfinished Composer", "hp": 168, "attack": 17, "defense": 16, "magic": 31, "spirit": 22, "speed": 24, "sprite_profile": &"composer_portrait_battle_actor", "actions": [&"unfinished_refrain", &"spectral_touch"], "elements": {&"lightning": 1.4, &"spectral": 0.45}, "exp": 44, "duckets": 16},
		&"haunted_doll": {"name": "Household Darling", "hp": 145, "attack": 27, "defense": 19, "magic": 22, "spirit": 17, "speed": 32, "sprite_profile": &"haunted_doll_battle_actor", "actions": [&"splinter_needle", &"nursery_wail"], "elements": {&"lightning": 1.25, &"spectral": 0.7}, "exp": 39, "duckets": 14},
		&"clock_mirror_boss": {"name": "The 4:44 Appointment", "hp": 720, "attack": 31, "defense": 24, "magic": 38, "spirit": 27, "speed": 27, "sprite_profile": &"clock_mirror_battle_actor", "actions": [&"steal_time", &"late_fee", &"spectral_touch"], "elements": {&"lightning": 1.35, &"time": 0.35, &"spectral": 0.5}, "status_resist": {&"poisoned": 1.0, &"slow": 0.65, &"shocked": 0.5}, "exp": 180, "duckets": 75},
		&"rift_jackal_challenger": {"name": "Rift Jackal, Fault-Line Stray", "hp": 1180, "attack": 40, "defense": 31, "magic": 28, "spirit": 26, "speed": 48, "sprite_profile": &"rift_jackal_battle_actor", "actions": [&"rift_bite", &"phase_scratch", &"faultline_pounce"], "elements": {&"spectral": 0.45, &"lightning": 1.3}, "status_resist": {&"poisoned": 0.65, &"slow": 0.5, &"shocked": 0.45}, "exp": 260, "duckets": 95, "battle_animation_root": "res://game_assets/characters/Topdown Monsters Part 1/Sliced/Rift Jackal", "battle_animation_fps": 8.0, "battle_animation_sequences": {&"idle": {"folder": "00_idle", "frames": 6}, &"attack": {"folder": "05_attack", "frames": 6}, &"hit": {"folder": "06_hit", "frames": 6}, &"power": {"folder": "07_blast_attack_1", "frames": 6}, &"victory": {"folder": "02_victory", "frames": 8}, &"death": {"folder": "12_death_1", "frames": 8}}, "battle_action_sequences": {&"rift_bite": &"attack", &"phase_scratch": &"power", &"faultline_pounce": &"attack"}},
		&"work_robot": {"name": "Overtime Work Robot", "hp": 132, "attack": 25, "defense": 22, "magic": 10, "spirit": 16, "speed": 22, "sprite_profile": &"work_robot_battle_actor", "actions": [&"servo_strike"], "elements": {&"lightning": 1.45}, "exp": 34, "duckets": 14},
		&"sentry_drone": {"name": "Union-Busting Sentry", "hp": 108, "attack": 23, "defense": 17, "magic": 19, "spirit": 14, "speed": 36, "sprite_profile": &"sentry_drone_battle_actor", "actions": [&"suppressive_burst", &"system_shock"], "elements": {&"lightning": 1.3}, "exp": 39, "duckets": 16},
		&"medical_robot": {"name": "Aggressive Care Unit", "hp": 176, "attack": 21, "defense": 25, "magic": 26, "spirit": 24, "speed": 24, "sprite_profile": &"medical_robot_battle_actor", "actions": [&"system_shock", &"servo_strike"], "elements": {&"lightning": 1.4}, "exp": 48, "duckets": 19},
		&"machine_commander": {"name": "Shift Supervisor", "hp": 245, "attack": 31, "defense": 29, "magic": 21, "spirit": 22, "speed": 27, "sprite_profile": &"machine_commander_battle_actor", "actions": [&"suppressive_burst", &"servo_strike"], "elements": {&"lightning": 1.25}, "exp": 66, "duckets": 26},
		&"mother_computer": {"name": "Mother Computer, Acting Manager", "hp": 1050, "attack": 33, "defense": 33, "magic": 43, "spirit": 30, "speed": 29, "sprite_profile": &"mother_computer_battle_actor", "actions": [&"mandatory_overtime", &"system_shock", &"suppressive_burst"], "elements": {&"lightning": 0.75}, "status_resist": {&"poisoned": 1.0, &"slow": 0.6, &"shocked": 0.45}, "exp": 260, "duckets": 110},
		&"bulkhead_warden_challenger": {"name": "Bulkhead Warden, Acting Shop Steward", "hp": 1420, "attack": 43, "defense": 48, "magic": 25, "spirit": 37, "speed": 20, "sprite_profile": &"bulkhead_warden_battle_actor", "actions": [&"warden_pummel", &"piston_surge", &"pressure_lock", &"bulkhead_drop"], "elements": {&"lightning": 1.35, &"nature": 0.65}, "status_resist": {&"poisoned": 1.0, &"slow": 0.62, &"shocked": 0.55}, "exp": 310, "duckets": 125, "battle_animation_root": "res://game_assets/characters/Topdown Monsters Part 1/Sliced/Bulkhead Warden", "battle_animation_fps": 8.0, "battle_animation_sequences": {&"idle": {"folder": "00_idle", "frames": 6}, &"attack": {"folder": "05_attack", "frames": 6}, &"hit": {"folder": "06_hit", "frames": 6}, &"power": {"folder": "08_blast_attack_2", "frames": 6}, &"victory": {"folder": "02_victory", "frames": 8}, &"death": {"folder": "12_death_1", "frames": 8}}, "battle_action_sequences": {&"warden_pummel": &"attack", &"piston_surge": &"power", &"pressure_lock": &"attack", &"bulkhead_drop": &"power"}},
		&"primeval_raptor": {"name": "Unlicensed Raptor", "hp": 178, "attack": 31, "defense": 18, "magic": 7, "spirit": 14, "speed": 42, "sprite_profile": &"primeval_raptor_battle_actor", "actions": [&"prehistoric_bite"], "elements": {&"lightning": 1.25}, "exp": 52, "duckets": 18},
		&"stone_triceratops": {"name": "Right-of-Way Triceratops", "hp": 310, "attack": 34, "defense": 34, "magic": 5, "spirit": 23, "speed": 19, "sprite_profile": &"stone_triceratops_battle_actor", "actions": [&"stampede", &"tail_sweep"], "elements": {&"lightning": 1.15}, "exp": 78, "duckets": 28},
		&"municipal_spinosaur": {"name": "Municipal Spinosaur", "hp": 275, "attack": 37, "defense": 25, "magic": 10, "spirit": 19, "speed": 29, "sprite_profile": &"municipal_spinosaur_battle_actor", "actions": [&"prehistoric_bite", &"tail_sweep"], "elements": {&"lightning": 1.2}, "exp": 84, "duckets": 31},
		&"commute_tyrant": {"name": "Tyrant of the Morning Commute", "hp": 1480, "attack": 43, "defense": 35, "magic": 18, "spirit": 29, "speed": 32, "sprite_profile": &"commute_tyrant_battle_actor", "actions": [&"commuter_roar", &"prehistoric_bite", &"tail_sweep"], "elements": {&"lightning": 1.25}, "status_resist": {&"poisoned": 0.75, &"slow": 0.65, &"shocked": 0.55}, "exp": 340, "duckets": 145},
		&"mossback_surveyor_challenger": {"name": "Mossback Surveyor, Unauthorized Planner", "hp": 1640, "attack": 45, "defense": 42, "magic": 35, "spirit": 39, "speed": 25, "sprite_profile": &"mossback_surveyor_battle_actor", "actions": [&"mossback_pummel", &"spore_receipt", &"rooted_red_tape"], "elements": {&"nature": 0.35, &"lightning": 1.3}, "status_resist": {&"poisoned": 0.2, &"slow": 0.6, &"shocked": 0.75}, "exp": 330, "duckets": 120, "battle_animation_root": "res://game_assets/characters/Topdown Monsters Part 1/Sliced/Mossback Surveyor", "battle_animation_fps": 8.0, "battle_animation_sequences": {&"idle": {"folder": "00_idle", "frames": 6}, &"attack": {"folder": "05_attack", "frames": 6}, &"hit": {"folder": "06_hit", "frames": 6}, &"power": {"folder": "08_blast_attack_2", "frames": 6}, &"victory": {"folder": "02_victory", "frames": 8}, &"death": {"folder": "12_death_1", "frames": 8}}, "battle_action_sequences": {&"mossback_pummel": &"attack", &"spore_receipt": &"power", &"rooted_red_tape": &"power"}},
		&"helios_mech": {"name": "Day-Shift Mech Soldier", "hp": 245, "attack": 38, "defense": 29, "magic": 17, "spirit": 21, "speed": 31, "sprite_profile": &"helios_mech_battle_actor", "actions": [&"compliance_burst", &"servo_strike"], "elements": {&"lightning": 1.35}, "exp": 76, "duckets": 30},
		&"helios_assassin": {"name": "Curfew Compliance Specialist", "hp": 205, "attack": 36, "defense": 23, "magic": 24, "spirit": 20, "speed": 46, "sprite_profile": &"helios_assassin_battle_actor", "actions": [&"compliance_burst", &"system_shock"], "elements": {&"lightning": 1.25}, "exp": 83, "duckets": 33},
		&"helios_security": {"name": "Public-Safety Optimizer", "hp": 330, "attack": 40, "defense": 38, "magic": 20, "spirit": 28, "speed": 24, "sprite_profile": &"helios_security_battle_actor", "actions": [&"suppressive_burst", &"daylight_lance"], "elements": {&"lightning": 1.2}, "exp": 102, "duckets": 41},
		&"helios_gunner": {"name": "Transit Fare Inspector", "hp": 260, "attack": 42, "defense": 27, "magic": 18, "spirit": 22, "speed": 35, "sprite_profile": &"helios_gunner_battle_actor", "actions": [&"suppressive_burst", &"compliance_burst"], "elements": {&"lightning": 1.3}, "exp": 96, "duckets": 39},
		&"civic_sun": {"name": "Civic Sun, Acting Mayor", "hp": 1950, "attack": 47, "defense": 41, "magic": 48, "spirit": 37, "speed": 34, "sprite_profile": &"civic_sun_battle_actor", "actions": [&"permanent_noon", &"daylight_lance", &"suppressive_burst"], "elements": {&"lightning": 1.25}, "status_resist": {&"poisoned": 1.0, &"slow": 0.6, &"shocked": 0.45}, "exp": 460, "duckets": 190},
		&"cobalt_courier_challenger": {"name": "Cobalt Courier, Undeliverable Agent", "hp": 2180, "attack": 50, "defense": 38, "magic": 52, "spirit": 40, "speed": 57, "sprite_profile": &"cobalt_courier_battle_actor", "actions": [&"cobalt_claw", &"express_jolt", &"priority_delivery"], "elements": {&"lightning": 1.25}, "status_resist": {&"poisoned": 0.7, &"slow": 0.5, &"shocked": 0.25}, "exp": 420, "duckets": 165, "battle_animation_root": "res://game_assets/characters/Topdown Monsters Part 1/Sliced/Cobalt Courier", "battle_animation_fps": 8.0, "battle_animation_sequences": {&"idle": {"folder": "00_idle", "frames": 6}, &"attack": {"folder": "05_attack", "frames": 6}, &"hit": {"folder": "06_hit", "frames": 6}, &"power": {"folder": "08_blast_attack_2", "frames": 6}, &"victory": {"folder": "02_victory", "frames": 8}, &"death": {"folder": "12_death_1", "frames": 8}}, "battle_action_sequences": {&"cobalt_claw": &"attack", &"express_jolt": &"power", &"priority_delivery": &"attack"}},
		&"frost_collector": {"name": "Royal Heat Collector", "hp": 315, "attack": 43, "defense": 34, "magic": 31, "spirit": 29, "speed": 31, "sprite_profile": &"frost_collector_battle_actor", "actions": [&"cold_assessment", &"servo_strike"], "elements": {&"frost": 0.45, &"lightning": 1.15}, "exp": 116, "duckets": 47},
		&"frost_necromancer": {"name": "Permafrost Assessor", "hp": 265, "attack": 27, "defense": 25, "magic": 46, "spirit": 38, "speed": 36, "sprite_profile": &"frost_necromancer_battle_actor", "actions": [&"lien_of_silence", &"cold_assessment"], "elements": {&"frost": 0.35, &"lightning": 1.35}, "exp": 124, "duckets": 51},
		&"ice_colossus": {"name": "Frozen Asset Seizure", "hp": 480, "attack": 49, "defense": 47, "magic": 24, "spirit": 35, "speed": 20, "sprite_profile": &"ice_colossus_battle_actor", "actions": [&"cold_assessment", &"tail_sweep"], "elements": {&"frost": 0.25, &"lightning": 1.35}, "exp": 158, "duckets": 64},
		&"whiteout_auditor": {"name": "Whiteout Auditor, Crown Receiver", "hp": 2450, "attack": 54, "defense": 46, "magic": 57, "spirit": 43, "speed": 37, "sprite_profile": &"whiteout_auditor_battle_actor", "actions": [&"absolute_audit", &"lien_of_silence", &"cold_assessment"], "elements": {&"frost": 0.2, &"lightning": 1.2}, "status_resist": {&"poisoned": 1.0, &"slow": 0.65, &"shocked": 0.5}, "exp": 590, "duckets": 245},
		&"memory_inspector": {"name": "Official Memory Inspector", "hp": 345, "attack": 40, "defense": 36, "magic": 48, "spirit": 39, "speed": 34, "sprite_profile": &"memory_inspector_battle_actor", "actions": [&"memory_stamp", &"spectral_touch"], "elements": {&"spectral": 0.45, &"lightning": 1.35}, "exp": 142, "duckets": 58},
		&"fox_attendant": {"name": "Counterfeit Wedding Attendant", "hp": 310, "attack": 46, "defense": 30, "magic": 37, "spirit": 31, "speed": 45, "sprite_profile": &"fox_attendant_battle_actor", "actions": [&"procession_waltz", &"memory_stamp"], "elements": {&"spectral": 0.5, &"lightning": 1.15}, "exp": 150, "duckets": 61},
		&"vow_spider": {"name": "Notarial Vow Spider", "hp": 540, "attack": 53, "defense": 42, "magic": 34, "spirit": 36, "speed": 27, "sprite_profile": &"vow_spider_battle_actor", "actions": [&"memory_stamp", &"splinter_needle"], "elements": {&"spectral": 0.65, &"lightning": 1.3}, "exp": 190, "duckets": 77},
		&"magistrate_enma": {"name": "Magistrate Enma, Keeper of the False Moon", "hp": 2920, "attack": 58, "defense": 49, "magic": 63, "spirit": 48, "speed": 40, "sprite_profile": &"magistrate_enma_battle_actor", "actions": [&"final_testimony", &"procession_waltz", &"memory_stamp"], "elements": {&"spectral": 0.25, &"lightning": 1.3}, "status_resist": {&"poisoned": 1.0, &"slow": 0.7, &"shocked": 0.55}, "exp": 720, "duckets": 310},
		&"crimson_oni_challenger": {"name": "Crimson Oni, Blood-Moon Challenger", "hp": 2650, "attack": 62, "defense": 45, "magic": 24, "spirit": 39, "speed": 51, "sprite_profile": &"crimson_oni_challenger_battle_actor", "actions": [&"oni_crescent", &"blood_moon_cleave"], "elements": {&"spectral": 0.55, &"lightning": 1.15}, "status_resist": {&"poisoned": 0.8, &"slow": 0.55, &"shocked": 0.45}, "exp": 680, "duckets": 280},
		&"wind_bailiff": {"name": "Wind Bailiff", "hp": 390, "attack": 51, "defense": 38, "magic": 45, "spirit": 40, "speed": 49, "sprite_profile": &"wind_bailiff_battle_actor", "actions": [&"gravity_writ", &"compliance_burst"], "elements": {&"radiant": 0.65, &"lightning": 1.15}, "exp": 172, "duckets": 70},
		&"storm_repossessor": {"name": "Storm-Wing Repossessor", "hp": 420, "attack": 48, "defense": 36, "magic": 55, "spirit": 42, "speed": 43, "sprite_profile": &"storm_repossessor_battle_actor", "actions": [&"storm_decree", &"gravity_writ"], "elements": {&"lightning": 1.2}, "exp": 184, "duckets": 75},
		&"fallen_notary": {"name": "Fallen Miracle Notary", "hp": 455, "attack": 34, "defense": 35, "magic": 61, "spirit": 48, "speed": 36, "sprite_profile": &"fallen_notary_battle_actor", "actions": [&"gravity_writ", &"daylight_lance"], "elements": {&"radiant": 0.45, &"lightning": 1.25}, "exp": 196, "duckets": 81},
		&"gravity_knight": {"name": "Elemental Lien Knight", "hp": 690, "attack": 60, "defense": 54, "magic": 45, "spirit": 44, "speed": 28, "sprite_profile": &"gravity_knight_battle_actor", "actions": [&"storm_decree", &"gravity_writ"], "elements": {&"lightning": 1.2}, "exp": 238, "duckets": 96},
		&"high_comptroller": {"name": "High Comptroller of Gravity", "hp": 3560, "attack": 64, "defense": 55, "magic": 70, "spirit": 54, "speed": 43, "sprite_profile": &"high_comptroller_battle_actor", "actions": [&"foreclosure_of_flight", &"storm_decree", &"gravity_writ"], "elements": {&"lightning": 1.2}, "status_resist": {&"poisoned": 1.0, &"slow": 0.72, &"shocked": 0.58}, "exp": 860, "duckets": 370},
	}


static func ids() -> Array[StringName]:
	var result: Array[StringName] = []
	for enemy_id in DEFINITIONS.keys():
		result.append(StringName(enemy_id))
	result.sort()
	return result


static func has(enemy_id: StringName) -> bool:
	return DEFINITIONS.has(enemy_id)


static func definition(enemy_id: StringName) -> Dictionary:
	return (DEFINITIONS.get(enemy_id, {}) as Dictionary).duplicate(true)


static func validate() -> PackedStringArray:
	var errors: Array[String] = []
	for enemy_id in ids():
		var record := definition(enemy_id)
		if String(record.get("name", "")).is_empty():
			errors.append("%s must have a display name." % enemy_id)
		if StringName(record.get("sprite_profile", &"")) == &"":
			errors.append("%s must reference an approved battle profile." % enemy_id)
		if (record.get("actions", []) as Array).is_empty():
			errors.append("%s must define at least one combat action." % enemy_id)
		if int(record.get("hp", 0)) <= 0 or int(record.get("exp", -1)) < 0 or int(record.get("duckets", -1)) < 0:
			errors.append("%s must define non-negative combat rewards and positive HP." % enemy_id)
	return PackedStringArray(errors)
