class_name FrostholdInteraction
extends Interaction

@export var interaction_kind: StringName = &"heat_tax_rune"


func _execute() -> void:
	var timeline := DialogicTimeline.new()
	timeline.events = apply_interaction()
	Dialogic.start_timeline(timeline)
	await Dialogic.timeline_ended


func apply_interaction(save_after := true) -> Array[String]:
	var events: Array[String]
	match interaction_kind:
		&"heat_tax_rune":
			events = _read_heat_tax_rune()
		&"causeway_seal":
			events = _warm_causeway_seal()
		&"throne_seal":
			events = _warm_throne_seal()
		&"save_brazier":
			CampaignState.activate_save_point(&"frosthold_rune_hall")
			events = ["A blue brazier records the route and restores the party. The flame is warm only after submitting the correct form."]
		_:
			events = ["The ice refuses to answer without a countersigned thermal declaration."]
	CampaignState.state_changed.emit()
	if save_after:
		CampaignState.save_game()
	return events


func _read_heat_tax_rune() -> Array[String]:
	if not CampaignState.story_flags.get(&"frost_lich_met", false):
		return ["ROYAL ASSESSMENT: ALL UNDECLARED BODY HEAT IS SUBJECT TO IMMEDIATE COLLECTION."]
	if CampaignState.story_flags.get(&"frosthold_rune_clue_found", false):
		return ["The rune permits a thermal exemption when warmth is generated by an instrument that can argue its own case."]
	CampaignState.story_flags[&"frosthold_rune_clue_found"] = true
	return [
		"FROST LICH EMPEROR: Clause forty-seven. An artificial heat source may petition for sovereign immunity.",
		"BEN: I have built several devices more argumentative than sovereigns.",
		"The Thermal Arbitration Coil can now be built in Ben's laboratory.",
	]


func _warm_causeway_seal() -> Array[String]:
	if &"thermal_arbitration_coil" not in CampaignState.owned_inventions:
		return ["The first seal freezes every ordinary tool to the ground. It accepts appeals only from self-heating machinery."]
	if CampaignState.story_flags.get(&"frosthold_causeway_seal_open", false):
		var revisited: Array[String] = ["The first seal remains legally and thermally open."]
		_append_thermal_assist(revisited)
		return revisited
	CampaignState.story_flags[&"frosthold_causeway_seal_open"] = true
	var events: Array[String] = ["Ben's Coil argues for warmth in seventeen clauses. The seal thaws halfway through clause three and opens the Rune Hall route."]
	_append_thermal_assist(events)
	return events


func _append_thermal_assist(events: Array[String]) -> void:
	var assist := CampaignState.claim_field_specialist_assist(&"frosthold_thermal_counsel")
	if bool(assist.get("granted", false)):
		events.append("%s catches the seal's occult waste heat before the royal treasury can repossess it." % String(assist.get("name", "A party specialist")))
		events.append(CampaignState.field_specialist_reward_text(assist))
	elif not bool(assist.get("claimed", false)):
		events.append(CampaignState.field_specialist_hint(&"frosthold_thermal_counsel"))


func _warm_throne_seal() -> Array[String]:
	if not CampaignState.story_flags.get(&"frosthold_rune_ambush_cleared", false):
		return ["The second seal is guarded by a collection detail with no interest in oral argument."]
	if &"thermal_arbitration_coil" not in CampaignState.owned_inventions:
		return ["The second seal requires Ben's Thermal Arbitration Coil."]
	if CampaignState.story_flags.get(&"frosthold_throne_open", false):
		return ["The Ice Throne route remains open. A distant auditor sharpens a very large pen."]
	CampaignState.story_flags[&"frosthold_throne_open"] = true
	CampaignState.restore_party()
	return ["The Coil voids the final thermal lien. The Ice Throne opens, and the party is fully restored before the audit."]
