extends Node

const REGISTRY := preload("res://ben_rpg/world/campaign_room_registry.gd")
const STREAMER_SCRIPT := preload("res://ben_rpg/world/campaign_room_streamer.gd")
const ROUTER := preload("res://ben_rpg/world/campaign_transition_router.gd")
const NAVIGATION_BUILDER := preload("res://ben_rpg/world/campaign_navigation_builder.gd")
const CAMERA_CONTROLLER_SCRIPT := preload("res://ben_rpg/world/campaign_camera_controller.gd")


func _ready() -> void:
	var registry_errors := REGISTRY.validate()
	var router_errors := ROUTER.validate()
	var navigation_errors := NAVIGATION_BUILDER.validate()
	assert(registry_errors.is_empty() and router_errors.is_empty() and navigation_errors.is_empty())
	var streamer: Node = STREAMER_SCRIPT.new()
	var camera_controller: Node = CAMERA_CONTROLLER_SCRIPT.new()
	add_child(streamer)
	add_child(camera_controller)
	camera_controller.call(&"bind_streamer", streamer)
	streamer.call(&"activate_room", &"TEST-01")
	assert(streamer.call(&"active_room_id") == &"TEST-01")
	var room: Node2D = streamer.call(&"active_root") as Node2D
	assert(room and room.has_node("GroundLayer") and room.has_node("NavigationAndCollision") and room.has_node("ForegroundLayer"))
	assert(room.has_node("InteractionLayer/ManifestInteraction"))
	assert(room.has_node("YSortedActorsAndProps/PopulationCohort"))
	var cohort := room.get_node("YSortedActorsAndProps/PopulationCohort")
	assert(cohort.get_meta(&"population_ids") == [&"test-room-caretaker"])
	var route := ROUTER.resolve(&"TEST-01", &"Nw")
	assert(StringName(route.get("destinationRoom", &"")) == &"TEST-01")
	assert(StringName(route.get("arrivalPort", &"")) == &"Ne")
	assert(room.has_node("InteractionLayer/SafeArrival_Ne"))
	var navigation := NAVIGATION_BUILDER.navigation_record(&"TEST-01")
	assert((navigation.get("walkable", {}) as Dictionary).has(route["arrivalCell"]))
	assert(NAVIGATION_BUILDER._legal_follower_cells(route["arrivalCell"], navigation.get("walkable", {}) as Dictionary) >= 3)
	assert(NAVIGATION_BUILDER._connected_component(route["arrivalCell"], navigation.get("walkable", {}) as Dictionary).has(Vector2i(7, 3)))
	assert(camera_controller.get("active_room_id") == &"TEST-01")
	assert(camera_controller.get("active_bounds") == Rect2i(0, 0, 672, 480))
	streamer.call(&"deactivate")
	assert(streamer.call(&"active_root") == null)
	assert(camera_controller.get("active_room_id") == &"")
	camera_controller.call(&"set_canvas_scale", Vector2(2.0, 2.0))
	streamer.call(&"activate_room", &"FR-03")
	assert(camera_controller.get("active_room_id") == &"FR-03")
	assert(camera_controller.get("active_bounds") == Rect2i(48000, 0, 2688, 1728))
	var camera := Camera2D.new()
	assert(camera_controller.call(&"apply_to", camera))
	assert(camera.limit_left == 48000 and camera.limit_right == 50688)
	assert(camera.limit_top == 0 and camera.limit_bottom == 1728)
	streamer.call(&"activate_legacy_mansion_area", &"mansion_foyer")
	assert(camera_controller.get("active_room_id") == &"")
	print("CAMPAIGN_MANIFEST_ROOM_SMOKE_OK scene=true unload=true camera=true scaled_camera=true navigation=true route=reciprocal features=true population=true")
	get_tree().quit()
