extends Node

const SETTINGS_REPOSITORY := preload("res://ben_rpg/core/settings_repository.gd")
const SAVE_REPOSITORY := preload("res://ben_rpg/core/save_repository.gd")
const TEST_PATH := "user://settings_repository_smoke.json"


func _ready() -> void:
	SAVE_REPOSITORY.cleanup(TEST_PATH)
	var repository := SETTINGS_REPOSITORY.new()
	var missing := repository.load_from_disk(TEST_PATH)
	assert(not bool(missing.get("ok", false)), "A missing settings file should use defaults without pretending it loaded")
	assert(is_equal_approx(float(repository.value(&"audio", &"master_volume")), 1.0), "Defaults should provide audio settings")
	repository.set_value(&"audio", &"master_volume", 4.0)
	repository.set_value(&"audio", &"ui_volume", -1.0)
	repository.set_value(&"audio", &"music_volume", 0.5)
	repository.set_value(&"audio", &"sfx_volume", 0.0)
	repository.set_value(&"display", &"fullscreen", true)
	repository.set_value(&"display", &"ui_scale", 1.25)
	repository.set_value(&"battle", &"atb_speed", 2.0)
	repository.set_value(&"battle", &"wait_mode", true)
	repository.set_value(&"accessibility", &"weather_density", -1.0)
	repository.set_value(&"accessibility", &"text_scale", 4.0)
	repository.set_value(&"accessibility", &"text_speed", 1.5)
	repository.set_value(&"accessibility", &"reduce_motion", true)
	repository.set_value(&"accessibility", &"reduce_flashes", true)
	repository.set_value(&"input", &"deadzone", 0.75)
	repository.set_value(&"input", &"vibration", false)
	assert(repository.save_to_disk(TEST_PATH) == OK, "Settings should save through the repository")
	var reloaded := SETTINGS_REPOSITORY.new()
	var loaded := reloaded.load_from_disk(TEST_PATH)
	assert(bool(loaded.get("ok", false)), "Settings should reload after saving")
	assert(is_equal_approx(float(reloaded.value(&"audio", &"master_volume")), 1.0), "Settings normalization should clamp audio")
	assert(is_equal_approx(float(reloaded.value(&"audio", &"ui_volume")), 0.0), "Settings normalization should preserve separate UI-volume limits")
	assert(is_equal_approx(float(reloaded.value(&"audio", &"music_volume")), 0.5), "Audio mix preferences should survive reload")
	assert(is_equal_approx(db_to_linear(AudioServer.get_bus_volume_db(AudioServer.get_bus_index(&"Music"))), 0.5), "Music volume should apply to the Music bus")
	assert(db_to_linear(AudioServer.get_bus_volume_db(AudioServer.get_bus_index(&"SFX"))) <= 0.0011, "SFX volume should apply to the SFX bus")
	assert(bool(reloaded.value(&"display", &"fullscreen")), "Fullscreen preference should survive reload without applying an OS mode in the repository")
	assert(is_equal_approx(float(reloaded.value(&"display", &"ui_scale")), 1.25), "Display scale preference should survive reload")
	assert(is_equal_approx(float(reloaded.value(&"battle", &"atb_speed")), 2.0), "Battle speed should survive reload")
	assert(bool(reloaded.value(&"battle", &"wait_mode")), "Battle mode should survive reload")
	assert(is_equal_approx(float(reloaded.value(&"accessibility", &"weather_density")), 0.0), "Settings normalization should clamp weather density")
	assert(is_equal_approx(float(reloaded.value(&"accessibility", &"text_scale")), 1.5), "Settings normalization should clamp text-scale preferences")
	assert(is_equal_approx(float(reloaded.value(&"accessibility", &"text_speed")), 1.5), "Text speed should survive reload")
	assert(is_equal_approx(float(Dialogic.Settings.get_setting("text_speed", 0.0)), 1.0 / 1.5), "Campaign text speed should apply to Dialogic's live reveal multiplier")
	assert(bool(reloaded.value(&"accessibility", &"reduce_motion")), "Reduced-motion preference should survive reload")
	assert(bool(reloaded.value(&"accessibility", &"reduce_flashes")), "Reduced-flash preference should survive reload")
	assert(is_equal_approx(float(reloaded.value(&"input", &"deadzone")), 0.75), "Settings should preserve valid preferences")
	assert(not bool(reloaded.value(&"input", &"vibration")), "Controller vibration preference should survive reload")
	reloaded.set_value(&"battle", &"atb_speed", 1.5)
	assert(reloaded.save_to_disk(TEST_PATH) == OK, "A second save should create a recoverable backup")
	var damaged := FileAccess.open(ProjectSettings.globalize_path(TEST_PATH), FileAccess.WRITE)
	damaged.store_string("{ not valid json")
	damaged.close()
	var recovered := SETTINGS_REPOSITORY.read_settings(TEST_PATH)
	assert(bool(recovered.get("ok", false)) and bool(recovered.get("recovered", false)), "Settings should recover a corrupt primary from backup")
	assert(is_equal_approx(float(recovered["settings"]["input"]["deadzone"]), 0.75), "Recovered settings should retain the previous complete payload")
	SAVE_REPOSITORY.cleanup(TEST_PATH)
	print("SETTINGS_REPOSITORY_SMOKE_OK defaults=typed accessibility+audio+display+battle+input=persisted normalized=true backup_recovery=true")
	get_tree().quit()
